branch-defaults:
  ec2-deployment:
    environment: Study-Group-2-dev
    group_suffix: null
global:
  application_name: Study_Group_2
  branch: null
  default_ec2_keyname: Study-group-ec2-creds
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
